name: Alveran
version: 1.2.0
description: Get celestical power
authors: [Kirastur]
website: https://www.spigotmc.org/resources/alveran-sudo.87291/

api-version: 1.16
load: POSTWORLD
main: de.polarwolf.alveran.main.Main
depend: [WorldEdit, WorldGuard, LuckPerms]

commands:
  alveran:
    description: Bless players
    permission: alveran.use
permissions:
  alveran.use:
    description: Should user be able to use the alveran command?
    default: op
  alveran.acolyte:
    description: Should user be able to retrieve the alveran blessing?
    default: false
