#
# Welcome to the Alveran configuration settings
#
# - Please see the pluing's homepage on Spigot for more information
# - https://www.spigotmc.org/resources/alveran-sudo.87291
# -
# -
# - The main purpose of this plugin is that a player
# - can accquire temporary permission by his own (like Linux "sudo").
# - Very useful in conjunction with LuckPerms "auto-op"
# - 
# - Usage:
# -   simply execute "/alveran" as a player or from a command block
# -
# - If called as a user, the user must have "alveran.use" permission
# - to be allowed to execute this command.
# -
# -
# - This plugin depends on LuckPerms, WorldGuard and LibSequence
# -
# - There is no auto-update for this plugin
# -


# startup
# 
# - Global settings only read at systemstart
startup:

   # Passive Mode
   #
   # - In passive mode the plugin engine is not initialized,
   # - only the Java objects are avail.
   # - You had to instanciate your own orchestratator
   # - and register it as API.
   # - Use this option only if you customize the Java objects itself.
   passiveMode: false
   
   # Enable Sanctuary
   #
   # - To avoid the use of CommandBlocks you can have an
   # - automatic trigger for alveran: Place a pressure plate
   # - inside your "alveran" region. Every time a player
   # - steps on this plate, the alveran blessing is executed,
   # - which means the checks for priest etc. are done,
   # - and - if fulfilled - the blessing is granted.
   enableSanctuary: false

   
 # General settings
general:

   # player-can-execute-command
   #
   # - Define if the "alveran" command can be executed by players.
   # - If not, only Console/RCON and command blocks can execute.
   # - The main purpose of Alveran is to be called by command blocks.
   player-can-execute-command: true
  
   # enableDebug
   #
   # - Print debug messages to console
   enableDebug: false
  
  
# Authentication (Protection)
#
# - We have a two-factor-authentication here
# - 1. Conscious decision (Player must stay in a specific region)
# - 2. Authorization (Player must have permission)
protection:

   # WorldGuard Region
   #
   # - The player must stay in a specific region to get blessed
   # - If more than one player with the appropriate permission stay
   # -  inside this region, all of them are blessed
   # - The Region must be defined in WorldGuard
   # - The flags of the region do not matter (e.g. passthrough)   
   region: alveran
  
   # actorPermission
   #
   # - At least on player with actorPermission mut stay inside the region
   # - to perform the blessing.
   # - Permission check is done by LuckPerms, so this plugin is mandantory
   # - The permission name is hard coded in plugin.yml
   # - so please change it here only if you know what you are doing
   actorPermission: alveran.priest

   # targetPermission
   #
   # - Only players having the receivePermission can be blessed.
   # - Permission check is done by LuckPerms, so this plugin is mandantory
   # - The permission name is hard coded in plugin.yml
   # - so please change it here only if you know what you are doing
   receivePermission: alveran.acolyte
   
   # IMPORTANT: A priest spends blessing, an acolyte receives it
   #
   # IF you want to bless yourself, you need both roles


# Action (Perform the blessing)
#
# - Define how the blessing looks like.
# - In general, a blessing is the temporary adding of a permission group
# -  to one or more players fulfilling the above criteria
action:

   # Destination Group
   #
   # - The name of the group which is temporary added to the players
   # - This group must already exists in LuckPerms
   # - It is added as a temporary group
   # - When the timer expires LuckPerms will remove membership automatically
   destination-group: alveran
  
   # Blessing duration
   #
   # - Define how log the player should be member of the the group
   # - Please enter an integer
   # - For Re-Blessing see LuckPerms config option "temporary-add-behaviour"
   # - Blessing is automatically removed if the player leaves the server
   blessing-duration-hours: 24
  
   # Player logout behaviour
   #
   # - Select what happens if the player is logging out
   # - If enabled on every login and logout Alveran checks membership
   # -  and removes the group from the player, regardless of the timer
   unbless-on-leave: true
  
   # Notify player about blessing timeout
   #
   # - Specify if the player should get noticed
   # -  when the blessing has reached its lifetime
   # -  and LuckPerms has removed the group from the player
   # -  (or the blessing was removed manually by a LuckPerm command)
   # -
   # - The bless and optional unbless whisper to the player are sent
   # -  regardless if the groupmembership was changed by Alveran 
   # -  or manually by a LuckPerms command or API call
   # -  so you can only use the notification part of Alveran
   # -  without using the command
   notify-on-unbless: true
   
   # Notify sound
   #
   # - Play a sound to the player when he receives the blessing 
   # - of Alveran. Enter a valid sound name from
   # - https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
   # - or an empty string for no sound
   notifySound: "UI_TOAST_CHALLENGE_COMPLETE"
   
